FROM adoptopenjdk/openjdk11:alpine-slim
RUN mkdir /opt/app

copy pshe-0.0.2.jar /opt/app/app.jar
ENV JAVA_OPTS=""
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /opt/app/app.jar" ]


